Persist ip config using coreos.inst.ip and coreos.inst.nameserver
coreos-installer reads `coreos.inst.ip` and `coreos.inst.nameserver` params,
generates ifcfg files and wraps around existing Ignition config.

diff --git a/coreos-installer b/coreos-installer
--- a/coreos-installer
+++ b/coreos-installer
@@ -513,6 +513,143 @@ get_ignition_url() {
     done
 }
 
+############################################################
+#Persist network configuration
+############################################################
+urlencode() {
+    local string="$(cat ${1})"
+    local strlen=${#string}
+    local encoded=""
+    local pos c o
+
+    for (( pos=0 ; pos<strlen ; pos++ )); do
+        c=${string:$pos:1}
+        case "$c" in
+            [-_.~a-zA-Z0-9] ) o="${c}" ;;
+            * )               printf -v o '%%%02x' "'$c"
+        esac
+        encoded+="${o}"
+    done
+    echo "${encoded}"
+}
+
+write_ifcfg_files() {
+    local IPS NAMESERVERS
+    if [ ! -f /tmp/ip ]; then
+        log "Not persisting network configs; none provided"
+        return
+    fi
+    type ip_to_var >/dev/null 2>&1 || . /lib/net-lib.sh
+    type strglobin >/dev/null 2>&1 || . /lib/dracut-lib.sh
+
+    IPS=($(cat /tmp/ip))
+    # Skip if no ips specified
+    [ ${#IPS[@]} == "0" ] && continue
+
+    log "Persisting provided network configs"
+    mkdir -p /tmp/ifcfg/
+
+    # Prepare nameservers list
+    NAMESERVERS=()
+    if [ -f /tmp/nameserver ]; then
+        NAMESERVERS=($(cat /tmp/nameservers))
+    fi
+
+    ignition_version="$(grep -Po '\"version\":\s\"\K([\d\\.]*)' /tmp/ignition.ign)"
+    case "${ignition_version}" in
+    "2.2.0")
+        log "Found ignition v2.2.0 in provided file"
+        ign_config_appendormerge="append"
+        ign_filesystem='"filesystem": "root",'
+        ;;
+    "3.0.0")
+        log "Found ignition v3.0.0 in provided file"
+        ign_config_appendormerge="merge"
+        ign_filesystem=''
+        ;;
+    *)
+        log "unknown distribution: unable to generate ifcfg files"
+        exit 1
+    esac
+    {
+        echo "{"
+        echo '  "ignition": {'
+        echo "   \"version\":\"${ignition_version}\""
+        echo '    "config": {'
+        echo "    \"${ign_config_appendormerge}\": [{"
+        echo "        \"source\": \"data:,$(urlencode /tmp/ignition.ign)\""
+        echo '  "storage": {'
+        echo '    "files": ['
+    } > /tmp/network.ign
+
+    network_ign=""
+    for p in ${IPS[@]}; do
+        ip_to_var $p
+        # Skip if no device specified
+        [ -z "$dev" ] && continue
+        # Skip ibft
+        [ "$autoconf" = "ibft" ] && continue
+        # Ignore complex configs
+        if [ -n "$bridge" ] || [ -n "$bond" ] || [ -n "$vlan" ] || [ -n "$team" ]; then continue; fi
+
+        {
+            echo "# Generated by coreos installer"
+            echo "DEVICE=\"$dev\""
+            echo "ONBOOT=yes"
+            case $autoconf in
+                dhcp|on|any|dhcp6)
+                    echo "BOOTPROTO=dhcp";;
+                *)
+                    echo "BOOTPROTO=none";;
+            esac
+            if strglobin "$ip" '*:*:*'; then
+                echo "IPV6INIT=yes"
+                echo "IPV6_AUTOCONF=no"
+                echo "IPV6ADDR=\"$ip/$mask\""
+            else
+                echo "IPADDR=\"$ip\""
+                if strstr "$mask" "."; then
+                    echo "NETMASK=\"$mask\""
+                else
+                    echo "PREFIX=\"$mask\""
+                fi
+            fi
+            if strglobin "$gw" '*:*:*'; then
+                echo "IPV6_DEFAULTGW=\"$gw\""
+            elif [ -n "$gw" ]; then
+                echo "GATEWAY=\"$gw\""
+            fi
+            [ -n "$mtu" ] && echo "MTU=\"$mtu\""
+
+            # Set DNS if core.inst.nameservers is set
+            i=1
+            for ns in ${NAMESERVERS[@]}; do
+                echo "DNS${i}=\"${ns}\""
+                i=$((i+1))
+            done
+        } > /tmp/ifcfg/ifcfg-$dev
+
+        # Transpile file and append its content to /tmp/network.ign
+        network_ign="${network_ign}{${ign_filesystem}\"path\": \"/etc/sysconfig/network-scripts/ifcfg-$dev\",\"mode\": 420,\"contents\": {\"source\": \"data:text/plain;charset=utf-8;$(urlencode /tmp/ifcfg/ifcfg-$dev)\"}},"
+
+        # Unset variables
+        unset dev
+        unset autoconf
+        unset ip
+        unset mask
+        unset gw
+        unset mtu
+    done
+
+    #  Skip if generated network_ign is empty
+    [ -z "$network_ign" ] && continue
+
+    # Complete ignition files and replace /tmp/ignition.ign with /tmp/network.ign
+    # Last symbol (comma) is being removed
+    echo "${network_ign%?}]}}" >> /tmp/network.ign
+    mv /tmp/network.ign /tmp/ignition.ign
+}
+
 #########################################################
 #Create the tmpfs filesystem to store the image
 #########################################################
@@ -715,6 +852,9 @@ main() {
     ####fi
     wipe_target_disk_labels
     write_image_to_disk
+
+    # If networking needs to be persisted write ifcfg's
+    write_ifcfg_files
 
     # If one was provided, install the ignition config
     write_ignition_file
